import os

DATA_ROOT = "/media/humpback/435806fd-079f-4ba1-ad80-109c8f6e2ec0/Ongoing/2026_LaneDetector/LaneDetector_on"
DATASET_PATH = DATA_ROOT + "/ade20k"  # holds original satellite images and color labels (for figures)

# Folder name for outputs (prediction JSON, CSV, Figure, Table). Change it per run to keep results separate.
RESULT_DIR = "results_260706"
RESULT_PATH = os.path.join(DATA_ROOT, RESULT_DIR)

# ────────────────────────────────────────────────────────────────────── #
# Original dataset (authoritative source): images, SEED vector labels, and split lists are all here.
#   image/        : satellite images {basename}.png across all splits (train+val+test = 12828)
#   label/        : SEED vector labels {basename}.json across all splits
#   dataset.json  : basename list per split (train/validation/test)
# ADE20K (images/validation) has only the val subset and no test, so the image/split source for
# inference and label generation always uses this original folder.
# ────────────────────────────────────────────────────────────────────── #
SRC_DATASET_PATH = os.path.join(DATA_ROOT, "satellite_good_matching_250206")
SRC_IMAGE_DIR = os.path.join(SRC_DATASET_PATH, "image")
SRC_LABEL_DIR = os.path.join(SRC_DATASET_PATH, "label")
DATASET_SPLIT_JSON = os.path.join(SRC_DATASET_PATH, "dataset.json")

# Splits to evaluate and the split->model prediction folder name mapping.
# Model inference saves the pure class-color masks to <model>/pred_val, <model>/pred_test
# (the former single 'prediction' folder is split per split).
EVAL_SPLITS = ['validation', 'test']
SPLIT_PRED_DIR = {'validation': 'pred_val', 'test': 'pred_test'}
# Short split label to append to output filenames and CSV columns (coco_pred_val_*, AP20(val), etc.)
SPLIT_LABEL = {'validation': 'val', 'test': 'test'}


def pred_dirname(split):
    """split -> model prediction mask subfolder name (pred_val / pred_test)."""
    return SPLIT_PRED_DIR[split]


def split_label(split):
    """split -> short label used in output filenames/columns (validation->val, test->test)."""
    return SPLIT_LABEL[split]


def mcol(metric, split):
    """Per-split metric column name. e.g. mcol('AP20','test') -> 'AP20(test)'."""
    return f"{metric}({SPLIT_LABEL[split]})"


def pred_path(model_path, split):
    """Per-split prediction mask folder path under the model directory."""
    return os.path.join(model_path, SPLIT_PRED_DIR[split])


def coco_anno_path(split):
    """Per-split COCO GT (merged_annotations_{split}.json) path (inside the result folder)."""
    return os.path.join(RESULT_PATH, f"merged_annotations_{split}.json")


def label_dir(split):
    """Per-split ADE20K index label (PNG) directory. Generated by rasterizing the SEED json."""
    return os.path.join(RESULT_PATH, "labels", split)


def merge_compare_dir(split):
    """Directory for saving merge_annotation before/after comparison images (per split)."""
    return os.path.join(RESULT_PATH, "merge_compare", split)


def split_result_path(split):
    """Algorithm result root. val/test are not split by path; they use the same RESULT_PATH.
    The two splits are distinguished only by filename (coco_pred_val_*/coco_pred_test_*) and CSV
    column suffix (…(val)/…(test)). (The argument is kept for caller compatibility, but the return
    value is identical regardless of split.)"""
    return RESULT_PATH


# ── validation default aliases for compatibility with existing scripts (Figure/Table, etc.) ── #
ANNO_DIR = RESULT_DIR
DATA_PATH = DATASET_PATH
LABEL_PATH = label_dir('validation')
COCO_MERGED_ANNO_PATH = coco_anno_path('validation')
COCO_ANNO_PATH = COCO_MERGED_ANNO_PATH

METAINFO = [
    {'id': 0, 'name': 'ignore', 'color': (0, 0, 0)},
    {'id': 1, 'name': 'center_line', 'color': (77, 77, 255)},
    {'id': 2, 'name': 'u_turn_zone_line', 'color': (77, 178, 255)},
    {'id': 3, 'name': 'lane_line', 'color': (77, 255, 77)},
    {'id': 4, 'name': 'bus_only_lane', 'color': (255, 153, 77)},
    {'id': 5, 'name': 'edge_line', 'color': (255, 77, 77)},
    {'id': 6, 'name': 'path_change_restriction_line', 'color': (178, 77, 255)},
    {'id': 7, 'name': 'no_parking_stopping_line', 'color': (77, 255, 178)},
    {'id': 8, 'name': 'guiding_line', 'color': (255, 178, 77)},
    {'id': 9, 'name': 'stop_line', 'color': (77, 102, 255)},
    {'id': 10, 'name': 'safety_zone', 'color': (255, 77, 128)},
    {'id': 11, 'name': 'bicycle_lane', 'color': (128, 255, 77)},
]
EXCLUDE_IDS = [0, 8, 10]   # bicycle_lane(11) included in evaluation
ID2BGR = {c['id']: (c['color'][2], c['color'][1], c['color'][0]) for c in METAINFO}
EVAL_CLASS_IDS = [c['id'] for c in METAINFO if c['id'] not in EXCLUDE_IDS]
ID2NAME = {c['id']: c['name'] for c in METAINFO}

RENDER_METAINFO = [
    {'id': 0, 'name': 'ignore', 'color': (0, 0, 0)},
    {'id': 1, 'name': 'center_line', 'color': (77, 77, 255)}, # original
    {'id': 2, 'name': 'u_turn_zone_line', 'color': (77, 178, 255)}, # original
    {'id': 3, 'name': 'lane_line', 'color': (77, 255, 77)}, # original
    {'id': 4, 'name': 'bus_only_lane', 'color': (255, 153, 77)}, # original
    {'id': 5, 'name': 'edge_line', 'color': (255, 77, 77)}, # original
    {'id': 6, 'name': 'path_change_restriction_line', 'color': (178, 77, 255)}, # original
    {'id': 7, 'name': 'no_parking_stopping_line', 'color': (77, 255, 178)}, # original
    {'id': 8, 'name': 'guiding_line', 'color': (255, 178, 77)}, # original
    {'id': 9, 'name': 'stop_line', 'color': (255, 215, 0)}, # Gold/Yellow color for high visual distinction against white background
    {'id': 10, 'name': 'safety_zone', 'color': (255, 77, 128)}, # original
    {'id': 11, 'name': 'bicycle_lane', 'color': (0, 139, 139)}, # Dark Cyan/Teal for high visual distinction against green and purple lines
]
RENDER_ID2BGR = {c['id']: (c['color'][2], c['color'][1], c['color'][0]) for c in RENDER_METAINFO}
MODEL_PREFIX = "satellite_ade20k_250925_"

# merge_annotation.py only: merges the separated SEED lane labels to build the COCO GT.
# The image/label/split lists reuse the original dataset (SRC_*) paths above as is.
SEED_LABEL_PATH = SRC_LABEL_DIR
